### ISSUE TITLE
PR#2をそのままマージするのはまずいです．

### ISSUE THREAD

**Issue by y-masutani** [OpenRTM/choreonoid-openrtm#3]
@n-ando PR #2 はそのままマージするのはまずいです．元に戻してください．それから，PRをしてからリポジトリを変にいじってしまって，他の差分も含まれています．申し訳ありません．

検討をお願いしたかったのは，コミットの https://github.com/OpenRTM/choreonoid-openrtm/commit/6dc9eb8548868f8445f16a468071be3088782df2 です．Windowsのそれも特定のパスに依存した強引な対処法ですので，このままでは他で通用しません．

**Comment by y-masutani** [comment]
@n-ando ひとまず 77596cb8f0c58d7f5b3291411a27e3e195169bfc にリセットしていただけないでしょうか．その後，PR#1をマージするのは問題ないと思います．PR#2はリジェクトしてください．できるかどうかわかりませんが，出直してきます．

**Comment by y-masutani** [comment]
```
target_link_libraries(${target} CnoidOpenRTMPlugin CnoidPyBase C:/Python37/Libs/python37.lib)
```
の代わりに
```
target_link_libraries(${target} CnoidOpenRTMPlugin CnoidPyBase ${PYTHON_LIBRARIES})
```
と書けば環境依存にはならないことはわかりましたが，`PYTHON_LIBRARIES` が定義されていません．`find_package(PythonLibs)` すれば変数を設定してくれますが，どこに書くのが正解かわかりません．Choreonoid本体では，
https://github.com/s-nakaoka/choreonoid/blob/master/CMakeLists.txt#L398-L434
辺りでやっていることではないかと思いますが，正確に把握できていません．問題になるのは，Choreonoid本体とは別にOpenRTMプラグインをビルドする場合だけかもしれません．その場合，`Choreonoidのインストールディレクトリ/share/choreonoid/cmake/ChoreonoidConfig.cmake` に`find_package(PythonLibs)` の結果が引き継がれていればいいのではないかと思いますが，そうはなっていないようです．

**Comment by y-masutani** [comment]
> その場合，Choreonoidのインストールディレクトリ/share/choreonoid/cmake/ChoreonoidConfig.cmake にfind_package(PythonLibs) の結果が引き継がれていればいいのではないかと思いますが，そうはなっていないようです．
Choreonoid本体の方で，上記を実現してもらいました．
https://github.com/s-nakaoka/choreonoid/pull/237
ですので
```
target_link_libraries(${target} CnoidOpenRTMPlugin CnoidPyBase ${CHOREONOID_PYTHON_LIBRARIES})
```
とすれば解決します．

**Comment by y-masutani** [comment]
@n-ando 様，PR #4 の件，ご検討をお願いいたします．

**Comment by n-ando** [comment]
すみません、見落としておりました。
PRの際、私にassignしていただけると、一覧に出ますのでよろしくお願いいたします。
